# Generated by Django 5.1.3 on 2026-03-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_alter_skill_options_alter_skill_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('testing', 'Testing'), ('deployment', 'Deployment')], max_length=20),
        ),
    ]
