# Generated by Django 5.1.3 on 2026-03-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_alter_skill_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
